participants:
  - el_type: gqrl
    el_image: qrl2-qns/go-qrl:pq-precompiles
    cl_type: qrysm
    cl_image: qrl2-qns/qrysm:beacon-chain-64
    use_separate_vc: true
    vc_type: qrysm
    vc_image: qrl2-qns/qrysm:validator-64
    validator_count: 64
    count: 1

network_params:
  network: kurtosis
  network_id: "3151908"
  withdrawal_address: "Q00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  seconds_per_slot: 6
  slots_per_epoch: 8
  genesis_delay: 30

wait_for_finalization: false
additional_services: []

qrl_genesis_generator_params:
  image: qrl2-qns/qrysm:qrl-genesis-generator-64

port_publisher:
  nat_exit_ip: "127.0.0.1"
  el:
    enabled: false
    public_port_start: 32000
  cl:
    enabled: false
    public_port_start: 33000
  vc:
    enabled: false
    public_port_start: 34000
  remote_signer:
    enabled: false
    public_port_start: 35000
  additional_services:
    enabled: false
    public_port_start: 36000
